
//
// Defines shader static allocation map (minimize constant transfer)
//

#define	BEGIN_CST			0

// Transfos
#define	PROJ_MATRIX_CST		(BEGIN_CST)
#define PROJ_MATRIX				GetMat4x4(PROJ_MATRIX_CST)
#define PROJ_MATRIX_SIZE	(4)
#define PROJ_MATRIX_END		(PROJ_MATRIX_CST+PROJ_MATRIX_SIZE)

#define	VIEW_MATRIX_CST		(PROJ_MATRIX_END)
#define VIEW_MATRIX				GetMat4x4(VIEW_MATRIX_CST)
#define VIEW_MATRIX_SIZE	(4)
#define VIEW_MATRIX_END		(VIEW_MATRIX_CST+VIEW_MATRIX_SIZE)

#define	WORLD_MATRIX_CST	(VIEW_MATRIX_END)
#define WORLD_MATRIX			GetMat4x4(WORLD_MATRIX_CST)
#define WORLD_MATRIX_SIZE	(4)
#define WORLD_MATRIX_END	(WORLD_MATRIX_CST+WORLD_MATRIX_SIZE)
